export interface TicketResponseDTO {
    IDBANCO: number,
    MENS_QUITADAS: "NAO" | "SIM",
    EMITIR_BOLETO: "SIM" | "NAO",
    CD_REC: number,
    VAL_REC: number,
    MES_EXTENSO: string,
    CD_LANCREC: string,
    NM_ALU: string,
    NM_RUA: string,
    NR_RUA: number,
    CEP_CID: number,
    NM_CID: string,
    UF_CID: string,
    ANO: number,
    MES: number,
    VENCIMENTO: string,
    DATA1_DESC: string,
    DATA2_DESC: string | null,
    DATA3_DESC: string | null,
    VALOR_TOT_DESC1: number,
    VALOR_TOT_DESC2: number,
    VALOR_TOT_DESC3: number
}