export interface UserInfoResponseDTO {
    "12521": string;
    CD_EMP: number;
    CD_CAN: number;
    CD_ALU: number;
    CD_CSO: number;
    CD_MAT: string;
    TURMA: number;
    CLASSE: string;
    SERIE: number;
    PER_GDE: number;
    ANO_MAT: number;
    SEM_MAT: number;
    SIT_ALUNO: string;
    CAUSA_SIT: string | null;
    NM_ALU: string;
    NM_RUA: string;
    NR_RUA: string;
    COMP_RUA: string;
    NM_BAI: string;
    CD_CID: number;
    CEP_CID: string;
    RG_PRO: string;
    CPF_PRO: string;
    CERT_MILITAR: string | null;
    TIT_ELEITOR: string | null;
    ZONA: string | null;
    SECAO: string | null;
    DT_NASC: string;
    SEXO: string;
    EST_CIVIL: number;
    NATURALIDADE: string | null;
    NACIONALIDADE: string | null;
    TEL_COM: string | null;
    TEL_RES: string;
    TEL_CEL: string;
    MAT_TRANSF: string;
    DT_MATRICULA: string;
    EMAIL: string;
    NM_PAI: string;
    PROFISSAO_PAI: string | null;
    NM_MAE: string;
    PROFISSAO_MAE: string | null;
    NM_CONJUGUE: string | null;
    NM_IESTRANS: string | null;
    CID_IESTRANS: string | null;
    ANO2MAT: number;
    ESCOLA2GRAU: string;
    CIDADE2GRAU: string | null;
    PROFISSAO: string;
    LOC_TRAB: string;
    END_TRAB: string | null;
    BAI_TRAB: string | null;
    CID_TRAB: string | null;
    CEP_TRAB: string | null;
    NM_RESP: string | null;
    END_RESP: string | null;
    CID_RESP: string | null;
    RG_RESP: string | null;
    CPF_RESP: string | null;
    DTNASC_RESP: string | null;
    TP_CURSO: string | null;
    PER_CURSO: string | null;
    ENTIDADE: string | null;
    MEDIA: string | null;
    CLASSIF: string | null;
    CD_GRADE: string | null;
    SEMVAL_MAT: number;
    ANOVAL_MAT: number;
    NUMPROT: string;
    LETPROT: string | null;
    FOTO_ALUNO: string;
    ANO_CAD: string | null;
    SEM_CAD: string | null;
    NREGDIPLOMA: string | null;
    LOCALREGISTRO: string | null;
    DT_CONCLUSAO: string;
    DT_COLACAO: string;
    DT_EXP_DIPLOMA: string | null;
    N_RGDIPIES: string;
    LIVRO: string;
    FOLHA: string;
    DT_REGISTRO: string | null;
    OBS: string | null;
    DT_VEST: string | null;
    DISC1: string;
    ANOVEST: string | null;
    DISC2: string;
    DISC3: string;
    DISC4: string;
    PONT1: string | null;
    PONT2: string | null;
    PONT3: string | null;
    PONT4: string | null;
    TOTPONT: string | null;
    N_REG_MEC: string | null;
    LIVRO_MEC: string | null;
    FOLHA_MEC: string | null;
    DT_REG_MEC: string | null;
    N_PROCESSO: string | null;
    N_ORDEM_IES: string | null;
    DT_PEDIDO: string | null;
    DT_ENV_RG: string | null;
    DT_ENT_DIP: string | null;
    CDT_PEDIDO: string | null;
    CDT_ENV_RG: string | null;
    CDT_REGISTRO: string | null;
    CDT_ENT_DIP: string | null;
    CP_RG: number;
    CP_NASCIMENTO: number;
    CP_RESERVISTA: number;
    CP_ELEITOR: number;
    CP_HISTORICO: number;
    CP_CPF: number;
    LOCAL_REGISTRO: string | null;
    DT_MON_PROC: string | null;
    N_ORDEM_MEC: string | null;
    CDT_MON_PROC: string | null;
    OBS_DIP: string | null;
    EX_NAC_CSO: string | null;
    DT_LIVRO_MEC: string | null;
    OBS_LIVRO_MEC: string | null;
    RET_REGISTRO: string | null;
    RET_DILIGENCIA: string | null;
    CONFEC_DIPLOMA: string | null;
    EMAILTESTE: string | null;
    STATUS_ATENDMKT: string | null;
    OBS_FINANCEIRO: string | null;
    WEBCODE: string | null;
    STATUS_BIBLI: string | null;
    STATUS_CANCMKT: string | null;
    ASTERISCO: string | null;
    CD_CANTEMP: string | null;
    CD_TIPO_ALUNO: number;
    STATUS_FOTO: string | null;
    SOUNDEX_NM_ALU: string | null;
    ATUALIZADO: string | null;
    ESTADO_NATURALIDADE: string | null;
    ENADE: string | null;
    ENADE_DT: string | null;
    COD_FIES: string | null;
    COD_PROUNI: string | null;
    CARTEIRINHA: string | null;
    TIPO_INGRESSO: number;
    CD_COR_RACA: string | null;
    NACIONALIDADE_CENSU: string | null;
    CD_CID_NASC: number;
    COD_PAIS_ORIGEM: string | null;
    ALU_DEFIC: number;
    TP_DEFIC_CEG: number;
    TP_DEFIC_BX_VS: number;
    TP_DEFIC_SURD: number;
    TP_DEFIC_AUD: number;
    TP_DEFIC_FIS: number;
    TP_DEFIC_SURD_CEG: number;
    TP_DEFIC_MULT: number;
    TP_DEFIC_MENT: number;
    TP_DEFIC_AUTIS: string | null;
    TP_DEFIC_SIND_ASP: string | null;
    TP_DEFIC_SIND_REET: string | null;
    TP_DEFIC_TRANS_DES: string | null;
    TP_DEFIC_ALTAS_HAB: string | null;
    FIES: number;
    FIES_REEMBOLS: number;
    FIES_FEDER: string | null;
    FIES_EST: number;
    FIES_MUN: number;
    FIES_IES: number;
    FIES_ENT_EXT: number;
    FIES_OUTR: number;
    PROUNI_INTEGR: number;
    PROUNI_PARCIAL: number;
    PROUNI_ESTADUAL: number;
    PROUNI_MUNIC: number;
    PROUNI_IES: number;
    PROUNI_ENT_EXT: number;
    PROUNI_OUTROS: number;
    APOIO_SOCIAL: number;
    AS_ALIM: number;
    AS_MORADIA: number;
    AS_TRANSP: number;
    AS_MAT_DIDAT: number;
    AS_BOLS_TRABAL: number;
    AS_BOLS_PERMAN: number;
    SUGESTAO: string | null;
    TIPO_ALUNO: string | null;
    ENVIAR_BOLETO: string | null;
    ALUNO_PROCEDENTE: number;
    DT_TERMINO_CSO: string | null;
    APRESAMENTO: string | null;
    LIBERACAO_FIN: string | null;
    LOGIN: number;
    EMISSAO_DOCS: number;
    OBS_DILIGENCIA: string | null;
    EXP_DILIGENCIA: string | null;
    PER_GDE_FIN: string | null;
    EMISSAO_BOLETO: string | null;
    NFE: string | null;
    CAR_HOR: string | null;
    CAR_HOR_PERC: string | null;
    "12521_1": number;
    DIP_DOU: string | null;
    DT_DIP_DOU: string | null;
    DIP_DOU_USU: string | null;
    ULTIMO_LOGIN: string;
    ANO_COLACAO: string | null;
    SEM_COLACAO: string | null;
    APTO_COLACAO: number;
    PRESENCA_COLACAO: number;
    CP_VACINA: number;
    CP_APOLICE: number;
    PER_GDE_INGRESSO: string | null;
    CP_ANALISE: number;
    ARTIGO_TEMA: string | null;
    ARTIGO_NOTA: string | null;
    SEM_DESC_PONT: number;
    NM_SOCIAL: string | null;
    EMAIL_FIN: string | null;
    ENEM_STATUS: number;
    ENEM_ANO: string | null;
    ENEM_NOTA: string | null;
    GOV_STATUS: string | null;
    PRESENCA_COLACAO_USU: string | null;
    COLACAO_PRESENCA_DTHR: string | null;
    DEF_FISICO: string | null;
    DEF_DESF: string | null;
    CANHOTO: string | null;
    ORGAOEXPEDITOR: string | null;
    RG_UF: string | null;
    RG_ORGAO: string | null;
    RG_DT_EMISSAO: string | null;
    UF_DIPLOMA: string | null;
    EST_DIPLOMA: string | null;
    ENADE_DT_ANO: string | null;
    ENADE_MOTIVO: string | null;
    ENADE_COND: string | null;
    SEGUNDA_VIA_DIP: string | null;
    NM_HAB: string;
    DT_HAB: string;
    HAB_HAB: number;
    ATUALIZA_ACESSO: number;
    NM_CID: string;

}